name: CI

on:
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.4.0
      with:
        node-version: 14.16.0
    
    - name: Install Twine & Build
      run: |
       pip install --upgrade twine build 
       
    - name: Build
      run: |
        python -m build
        
    - name: Upload
      env:
        TWINE_USERNAME: amirbilu
        TWINE_PASSWORD: ${{ github.secrets.TWINE_PASSWORD }} 
      run: |
        python -m twine upload dist/*

